import type { FlowChunk } from '$lib/types/flow';

/**
 * Built-in chunk definitions that ship with the IDE.
 * These are pre-built node templates users can drag into their flow graphs.
 */
export const BUILTIN_CHUNKS: FlowChunk[] = [
	{
		id: 'builtin-intro-screen',
		name: 'Intro Screen',
		description: 'A splash/intro screen with a timeout transition to the next state.',
		category: 'intro',
		tags: ['intro', 'splash', 'startup'],
		nodeTemplate: {
			type: 'intro',
			label: 'Intro',
			gpcCode: '// Intro screen — auto-transitions after timeout',
			onEnter: 'cls_oled(OLED_BLACK);',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Timeout',
				condition: { type: 'timeout', timeoutMs: 3000 },
				direction: 'outgoing',
			},
		],
		parameters: [
			{
				key: 'timeoutMs',
				label: 'Duration (ms)',
				type: 'number',
				defaultValue: '3000',
				description: 'How long to show the intro before transitioning',
			},
		],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-menu-3items',
		name: 'Menu Page (3 Items)',
		description: 'A standard 3-item OLED menu page with up/down navigation and confirm/cancel.',
		category: 'menu',
		tags: ['menu', 'navigation', 'oled'],
		nodeTemplate: {
			type: 'menu',
			label: 'Main Menu',
			variables: [],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-menu3-header',
					type: 'header',
					label: 'MENU',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-menu3-item1',
					type: 'menu-item',
					label: 'Item 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-menu3-item2',
					type: 'menu-item',
					label: 'Item 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-menu3-item3',
					type: 'menu-item',
					label: 'Item 3',
					position: 'stack',
					order: 3,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Confirm',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Cancel',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-settings-submenu',
		name: 'Settings Submenu',
		description: 'A submenu with toggle options and a cancel/back button.',
		category: 'menu',
		tags: ['settings', 'submenu', 'options'],
		nodeTemplate: {
			type: 'submenu',
			label: 'Settings',
			variables: [
				{ name: 'Setting1', type: 'bool', defaultValue: 0, persist: true, min: 0, max: 1 },
				{ name: 'Setting2', type: 'bool', defaultValue: 0, persist: true, min: 0, max: 1 },
			],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-settings-header',
					type: 'header',
					label: 'SETTINGS',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-settings-toggle1',
					type: 'toggle-item',
					label: 'Option 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', onText: 'ON', offText: 'OFF', valueAlign: 'right', font: 'default' },
					boundVariable: 'Setting1',
				},
				{
					id: 'chunk-settings-toggle2',
					type: 'toggle-item',
					label: 'Option 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', onText: 'ON', offText: 'OFF', valueAlign: 'right', font: 'default' },
					boundVariable: 'Setting2',
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-screensaver',
		name: 'Screensaver',
		description: 'A simple screensaver state that activates after idle timeout and wakes on any button.',
		category: 'screensaver',
		tags: ['screensaver', 'idle', 'sleep'],
		nodeTemplate: {
			type: 'screensaver',
			label: 'Screensaver',
			gpcCode: '// Screensaver — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Wake',
				condition: { type: 'custom', customCode: 'event_press(PS5_CROSS) || event_press(PS5_CIRCLE)' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-splash-timed',
		name: 'Splash Screen',
		description: 'A timed splash screen showing a title and subtitle, then auto-transitions.',
		category: 'intro',
		tags: ['splash', 'title', 'intro'],
		nodeTemplate: {
			type: 'intro',
			label: 'Splash',
			gpcCode: '// Splash — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Timeout',
				condition: { type: 'timeout', timeoutMs: 2000 },
				direction: 'outgoing',
			},
			{
				label: 'Skip',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
		],
		parameters: [
			{
				key: 'timeoutMs',
				label: 'Duration (ms)',
				type: 'number',
				defaultValue: '2000',
				description: 'How long to show the splash',
			},
		],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-home-status',
		name: 'Home / Status Screen',
		description: 'A home/status screen showing the current state of toggles, with menu button access.',
		category: 'home',
		tags: ['home', 'status', 'main'],
		nodeTemplate: {
			type: 'home',
			label: 'Home',
			gpcCode: '// Home status — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Open Menu',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-vm-speed',
		name: 'VM Speed',
		description:
			'Sets the VM polling speed per platform. Auto-creates a menu submenu with speed presets: 10ms, 8ms, 4ms, 2ms, 1ms. Add this to your Gameplay flow.',
		category: 'utility',
		tags: ['vm', 'speed', 'polling', 'settings', 'vm_tctrl'],
		flowType: 'gameplay',
		nodeTemplate: {
			type: 'module',
			label: 'VM Speed',
			variables: [
				{ name: 'VMSpeedIndex', type: 'int', defaultValue: 0, persist: true, min: 0, max: 4 },
			],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			moduleData: {
				moduleId: 'vm_speed',
				moduleName: 'VM Speed',
				triggerCondition: '',
				enableVariable: '',
				alwaysActive: true,
				initCode: 'ApplyVMSpeed();',
				mainCode: 'ApplyVMSpeed();',
				functionsCode: [
					'const string VMSpeedLabels[] = { "10ms", "8ms", "4ms", "2ms", "1ms" };',
					'',
					'function ApplyVMSpeed() {',
					'    if (VMSpeedIndex == 0) { vm_tctrl(0); }',
					'    else if (VMSpeedIndex == 1) { vm_tctrl(-2); } // 8ms Xbox One',
					'    else if (VMSpeedIndex == 2) { vm_tctrl(-6); } // 4ms PS4/PS5',
					'    else if (VMSpeedIndex == 3) { vm_tctrl(-8); } // 2ms Xbox X/S',
					'    else if (VMSpeedIndex == 4) { vm_tctrl(-9); } // 1ms PC',
					'}',
				].join('\n'),
				comboCode: '',
				options: [
					{
						name: 'Speed',
						variable: 'VMSpeedIndex',
						type: 'array',
						defaultValue: 0,
						min: 0,
						max: 4,
						arrayName: 'VMSpeedLabels',
						arraySize: 5,
						onChangeCode: 'ApplyVMSpeed();',
					},
				],
				extraVars: {},
				conflicts: [],
				needsWeapondata: false,
				shortDescription: 'Polling rate (10ms/8ms/4ms/2ms/1ms)',
			},
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-custom-gameplay',
		name: 'Custom',
		description:
			'An empty gameplay module. Rename it, add your custom code, and create a module through the flow tab.',
		category: 'utility',
		tags: ['custom', 'gameplay', 'module', 'blank'],
		flowType: 'gameplay',
		nodeTemplate: {
			type: 'module',
			label: 'Custom',
			variables: [
				{
					name: 'Custom_Enabled',
					type: 'bool',
					defaultValue: 0,
					persist: true,
					min: 0,
					max: 1,
				},
			],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			moduleData: {
				moduleId: 'custom',
				moduleName: 'Custom',
				triggerCondition: '',
				enableVariable: 'Custom_Enabled',
				initCode: '',
				mainCode: '// Add your main loop code here',
				functionsCode: '// Add your functions here',
				comboCode: '',
				options: [],
				extraVars: {},
				conflicts: [],
				needsWeapondata: false,
			},
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-custom-data',
		name: 'Custom',
		description:
			'An empty data module. Rename it and add your custom data definitions.',
		category: 'utility',
		tags: ['custom', 'data', 'module', 'blank'],
		flowType: 'data',
		nodeTemplate: {
			type: 'module',
			label: 'Custom',
			variables: [],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			moduleData: {
				moduleId: 'custom',
				moduleName: 'Custom',
				triggerCondition: '',
				enableVariable: '',
				alwaysActive: true,
				initCode: '',
				mainCode: '// Add your data code here',
				functionsCode: '// Add your functions here',
				comboCode: '',
				options: [],
				extraVars: {},
				conflicts: [],
				needsWeapondata: false,
				flowTarget: 'data',
			},
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	// ==================== Converted from Code Generators ====================

	{
		id: 'builtin-custom-node',
		name: 'Custom Node',
		description: 'A blank custom node with raw GPC code sections for render, onEnter/onExit, and combos.',
		category: 'utility',
		tags: ['custom', 'code', 'blank', 'raw'],
		flowType: 'menu',
		nodeTemplate: {
			type: 'custom',
			label: 'Custom',
			gpcCode: '// Main render/logic — runs each cycle while in this state',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Next',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-menu-multipage',
		name: 'Multi-Page Menu',
		description: 'A menu page with next/prev page cycling and confirm/back navigation.',
		category: 'menu',
		tags: ['oled', 'menu', 'navigation', 'cycling', 'multipage'],
		nodeTemplate: {
			type: 'menu',
			label: 'Menu Page',
			variables: [],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-multipage-header',
					type: 'header',
					label: 'PAGE TITLE',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-multipage-item1',
					type: 'menu-item',
					label: 'Item 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-multipage-item2',
					type: 'menu-item',
					label: 'Item 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-multipage-item3',
					type: 'menu-item',
					label: 'Item 3',
					position: 'stack',
					order: 3,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Next Page',
				condition: { type: 'button_press', button: 'PS5_DOWN' },
				direction: 'outgoing',
			},
			{
				label: 'Prev Page',
				condition: { type: 'button_press', button: 'PS5_UP' },
				direction: 'outgoing',
			},
			{
				label: 'Confirm',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-timeline-recoil-debug',
		name: 'Timeline Recoil Debug',
		description:
			'Debug node for testing anti-recoil timeline phase values on the fly. Lets you select a phase (0-9), adjust V/H values, and see changes reflected live. Requires antirecoil_timeline module. Changes are not persisted.',
		category: 'debug',
		tags: ['recoil', 'timeline', 'debug', 'antirecoil', 'weapons', 'phases'],
		nodeTemplate: {
			type: 'debug',
			label: 'Recoil Debug',
			variables: [
				{ name: 'TLDebug_Phase', type: 'int', defaultValue: 0, persist: false },
				{ name: 'TLDebug_V', type: 'int', defaultValue: 0, persist: false },
				{ name: 'TLDebug_H', type: 'int', defaultValue: 0, persist: false },
				{ name: 'TLDebug_Clear', type: 'int', defaultValue: 0, persist: false },
				{ name: '_tld_i', type: 'int', defaultValue: 0, persist: false },
				{ name: '_tld_bh', type: 'int', defaultValue: 0, persist: false },
			],
			gpcCode: [
				'// Clear all phases',
				'if(TLDebug_Clear) {',
				'    for(_tld_i = 0; _tld_i < 10; _tld_i++) { _recoil_phase_v[_tld_i] = 0; _recoil_phase_h[_tld_i] = 0; }',
				'    TLDebug_V = 0; TLDebug_H = 0; TLDebug_Clear = FALSE; FlowRedraw = TRUE;',
				'}',
				'',
				'// Two-way sync: array <-> shadow vars',
				'if(_recoil_phase_v[TLDebug_Phase] != TLDebug_V) { TLDebug_V = _recoil_phase_v[TLDebug_Phase]; FlowRedraw = TRUE; }',
				'if(_recoil_phase_h[TLDebug_Phase] != TLDebug_H) { TLDebug_H = _recoil_phase_h[TLDebug_Phase]; FlowRedraw = TRUE; }',
				'',
				'// Weapon name',
				'print(2, 35, OLED_FONT_SMALL, OLED_WHITE, Weapons[active_weapon]);',
				'',
				'// Timeline bar chart (V values by phase)',
				'line_oled(0, 43, 127, 43, 1, OLED_WHITE);',
				'for(_tld_i = 0; _tld_i < 10; _tld_i++) {',
				'    _tld_bh = abs(_recoil_phase_v[_tld_i]) * 18 / 100;',
				'    if(_tld_bh > 0) {',
				'        rect_oled(_tld_i * 12 + 4, 63 - _tld_bh, 10, _tld_bh, 1, OLED_WHITE);',
				'    }',
				'    // Mark current phase',
				'    if(_tld_i == TLDebug_Phase) {',
				'        rect_oled(_tld_i * 12 + 4, 44, 10, 1, 1, OLED_WHITE);',
				'    }',
				'}',
			].join('\n'),
			onEnter:
				'LoadRecoilPhases(active_weapon);\nTLDebug_Phase = 0;\nTLDebug_V = _recoil_phase_v[0];\nTLDebug_H = _recoil_phase_h[0];',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-tld-header',
					type: 'header',
					label: 'RECOIL DEBUG',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-tld-phase',
					type: 'value-item',
					label: 'Phase',
					position: 'stack',
					order: 1,
					interactive: true,
					boundVariable: 'TLDebug_Phase',
					config: {
						cursorStyle: 'invert',
						prefixChar: '>',
						prefixSpacing: 1,
						min: 0,
						max: 9,
						step: 1,
						valueAlign: 'right',
						valueMargin: 0,
						format: '{value}',
						font: 'default',
						onChangeCode:
							'TLDebug_V = _recoil_phase_v[TLDebug_Phase]; TLDebug_H = _recoil_phase_h[TLDebug_Phase];',
					},
				},
				{
					id: 'chunk-tld-v',
					type: 'value-item',
					label: 'Vertical',
					position: 'stack',
					order: 2,
					interactive: true,
					boundVariable: 'TLDebug_V',
					config: {
						cursorStyle: 'invert',
						prefixChar: '>',
						prefixSpacing: 1,
						min: -100,
						max: 100,
						step: 1,
						valueAlign: 'right',
						valueMargin: 0,
						format: '{value}',
						font: 'default',
						onChangeCode: '_recoil_phase_v[TLDebug_Phase] = TLDebug_V;',
					},
				},
				{
					id: 'chunk-tld-h',
					type: 'value-item',
					label: 'Horizontal',
					position: 'stack',
					order: 3,
					interactive: true,
					boundVariable: 'TLDebug_H',
					config: {
						cursorStyle: 'invert',
						prefixChar: '>',
						prefixSpacing: 1,
						min: -100,
						max: 100,
						step: 1,
						valueAlign: 'right',
						valueMargin: 0,
						format: '{value}',
						font: 'default',
						onChangeCode: '_recoil_phase_h[TLDebug_Phase] = TLDebug_H;',
					},
				},
				{
					id: 'chunk-tld-clear',
					type: 'toggle-item',
					label: 'Clear',
					position: 'stack',
					order: 4,
					interactive: true,
					boundVariable: 'TLDebug_Clear',
					config: {
						cursorStyle: 'invert',
						prefixChar: '>',
						prefixSpacing: 1,
						onText: '...',
						offText: '---',
						valueAlign: 'right',
						valueMargin: 0,
						font: 'default',
					},
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-digital-clock',
		name: 'Digital Clock',
		description: 'OLED digital clock display with hours, minutes, seconds and blinking colon.',
		category: 'code',
		tags: ['oled', 'clock', 'display', 'timer'],
		nodeTemplate: {
			type: 'custom',
			label: 'Clock',
			variables: [
				{ name: 'clock_hours', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_minutes', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_seconds', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_timer', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_colon_on', type: 'int', defaultValue: 1, persist: false },
			],
			gpcCode: [
				'// ========== Digital Clock Display ==========',
				'ClockTick();',
				'DrawClock();',
				'',
				'function ClockTick() {',
				'    clock_timer = clock_timer + get_rtime();',
				'    if(clock_timer >= 1000) {',
				'        clock_timer = clock_timer - 1000;',
				'        clock_seconds = clock_seconds + 1;',
				'        if(clock_seconds >= 60) {',
				'            clock_seconds = 0;',
				'            clock_minutes = clock_minutes + 1;',
				'            if(clock_minutes >= 60) {',
				'                clock_minutes = 0;',
				'                clock_hours = clock_hours + 1;',
				'                if(clock_hours >= 24) clock_hours = 0;',
				'            }',
				'        }',
				'        clock_colon_on = !clock_colon_on;',
				'    }',
				'}',
				'',
				'function DrawClock() {',
				'    // Hours',
				'    PrintNumber(clock_hours / 10, 1, 24, 20, OLED_FONT_MEDIUM);',
				'    PrintNumber(clock_hours % 10, 1, 36, 20, OLED_FONT_MEDIUM);',
				'',
				'    // Blinking colon',
				'    if(clock_colon_on) {',
				'        pixel_oled(50, 23, 1);',
				'        pixel_oled(50, 27, 1);',
				'    }',
				'',
				'    // Minutes',
				'    PrintNumber(clock_minutes / 10, 1, 54, 20, OLED_FONT_MEDIUM);',
				'    PrintNumber(clock_minutes % 10, 1, 66, 20, OLED_FONT_MEDIUM);',
				'',
				'    // Seconds (smaller)',
				'    PrintNumber(clock_seconds / 10, 1, 82, 24, OLED_FONT_SMALL);',
				'    PrintNumber(clock_seconds % 10, 1, 88, 24, OLED_FONT_SMALL);',
				'}',
			].join('\n'),
			onEnter: 'clock_timer = 0;',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
];

export function getBuiltinChunk(id: string): FlowChunk | undefined {
	return BUILTIN_CHUNKS.find((c) => c.id === id);
}

export function getChunksByCategory(chunks: FlowChunk[]): Record<string, FlowChunk[]> {
	const grouped: Record<string, FlowChunk[]> = {};
	for (const chunk of chunks) {
		const cat = chunk.category || 'uncategorized';
		if (!grouped[cat]) grouped[cat] = [];
		grouped[cat].push(chunk);
	}
	return grouped;
}
