import type { FlowChunk } from '$lib/types/flow';

/**
 * Built-in chunk definitions that ship with the IDE.
 * These are pre-built node templates users can drag into their flow graphs.
 */
export const BUILTIN_CHUNKS: FlowChunk[] = [
	{
		id: 'builtin-intro-screen',
		name: 'Intro Screen',
		description: 'A splash/intro screen with a timeout transition to the next state.',
		category: 'intro',
		tags: ['intro', 'splash', 'startup'],
		nodeTemplate: {
			type: 'intro',
			label: 'Intro',
			gpcCode: '// Intro screen — auto-transitions after timeout',
			onEnter: 'cls_oled(OLED_BLACK);',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Timeout',
				condition: { type: 'timeout', timeoutMs: 3000 },
				direction: 'outgoing',
			},
		],
		parameters: [
			{
				key: 'timeoutMs',
				label: 'Duration (ms)',
				type: 'number',
				defaultValue: '3000',
				description: 'How long to show the intro before transitioning',
			},
		],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-menu-3items',
		name: 'Menu Page (3 Items)',
		description: 'A standard 3-item OLED menu page with up/down navigation and confirm/cancel.',
		category: 'menu',
		tags: ['menu', 'navigation', 'oled'],
		nodeTemplate: {
			type: 'menu',
			label: 'Main Menu',
			variables: [],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-menu3-header',
					type: 'header',
					label: 'MENU',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-menu3-item1',
					type: 'menu-item',
					label: 'Item 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-menu3-item2',
					type: 'menu-item',
					label: 'Item 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-menu3-item3',
					type: 'menu-item',
					label: 'Item 3',
					position: 'stack',
					order: 3,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Confirm',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Cancel',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-settings-submenu',
		name: 'Settings Submenu',
		description: 'A submenu with toggle options and a cancel/back button.',
		category: 'menu',
		tags: ['settings', 'submenu', 'options'],
		nodeTemplate: {
			type: 'submenu',
			label: 'Settings',
			variables: [
				{ name: 'Setting1', type: 'int', defaultValue: 0, persist: true },
				{ name: 'Setting2', type: 'int', defaultValue: 0, persist: true },
			],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-settings-header',
					type: 'header',
					label: 'SETTINGS',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-settings-toggle1',
					type: 'toggle-item',
					label: 'Option 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', onText: 'ON', offText: 'OFF', valueAlign: 'right', font: 'default' },
					boundVariable: 'Setting1',
				},
				{
					id: 'chunk-settings-toggle2',
					type: 'toggle-item',
					label: 'Option 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', onText: 'ON', offText: 'OFF', valueAlign: 'right', font: 'default' },
					boundVariable: 'Setting2',
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-screensaver',
		name: 'Screensaver',
		description: 'A simple screensaver state that activates after idle timeout and wakes on any button.',
		category: 'screensaver',
		tags: ['screensaver', 'idle', 'sleep'],
		nodeTemplate: {
			type: 'screensaver',
			label: 'Screensaver',
			gpcCode: '// Screensaver — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Wake',
				condition: { type: 'custom', customCode: 'event_press(PS5_CROSS) || event_press(PS5_CIRCLE)' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-splash-timed',
		name: 'Splash Screen',
		description: 'A timed splash screen showing a title and subtitle, then auto-transitions.',
		category: 'intro',
		tags: ['splash', 'title', 'intro'],
		nodeTemplate: {
			type: 'intro',
			label: 'Splash',
			gpcCode: '// Splash — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Timeout',
				condition: { type: 'timeout', timeoutMs: 2000 },
				direction: 'outgoing',
			},
			{
				label: 'Skip',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
		],
		parameters: [
			{
				key: 'timeoutMs',
				label: 'Duration (ms)',
				type: 'number',
				defaultValue: '2000',
				description: 'How long to show the splash',
			},
		],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-home-status',
		name: 'Home / Status Screen',
		description: 'A home/status screen showing the current state of toggles, with menu button access.',
		category: 'home',
		tags: ['home', 'status', 'main'],
		nodeTemplate: {
			type: 'home',
			label: 'Home',
			gpcCode: '// Home status — add pixel art sub-nodes for visuals',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Open Menu',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	// ==================== Converted from Code Generators ====================

	{
		id: 'builtin-custom-node',
		name: 'Custom Node',
		description: 'A blank custom node with raw GPC code sections for render, onEnter/onExit, and combos.',
		category: 'utility',
		tags: ['custom', 'code', 'blank', 'raw'],
		nodeTemplate: {
			type: 'custom',
			label: 'Custom',
			gpcCode: '// Main render/logic — runs each cycle while in this state',
			onEnter: '',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [
			{
				label: 'Next',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-menu-multipage',
		name: 'Multi-Page Menu',
		description: 'A menu page with next/prev page cycling and confirm/back navigation.',
		category: 'menu',
		tags: ['oled', 'menu', 'navigation', 'cycling', 'multipage'],
		nodeTemplate: {
			type: 'menu',
			label: 'Menu Page',
			variables: [],
			gpcCode: '',
			onEnter: '',
			onExit: '',
			comboCode: '',
			stackOffsetX: 0,
			stackOffsetY: 0,
			subNodes: [
				{
					id: 'chunk-multipage-header',
					type: 'header',
					label: 'PAGE TITLE',
					position: 'stack',
					order: 0,
					interactive: false,
					config: { align: 'left', font: 'default', separator: true, paddingTop: 0 },
				},
				{
					id: 'chunk-multipage-item1',
					type: 'menu-item',
					label: 'Item 1',
					position: 'stack',
					order: 1,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-multipage-item2',
					type: 'menu-item',
					label: 'Item 2',
					position: 'stack',
					order: 2,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
				{
					id: 'chunk-multipage-item3',
					type: 'menu-item',
					label: 'Item 3',
					position: 'stack',
					order: 3,
					interactive: true,
					config: { cursorStyle: 'invert', prefixChar: '>', prefixSpacing: 1, font: 'default' },
				},
			],
		},
		edgeTemplates: [
			{
				label: 'Next Page',
				condition: { type: 'button_press', button: 'PS5_DOWN' },
				direction: 'outgoing',
			},
			{
				label: 'Prev Page',
				condition: { type: 'button_press', button: 'PS5_UP' },
				direction: 'outgoing',
			},
			{
				label: 'Confirm',
				condition: { type: 'button_press', button: 'PS5_CROSS' },
				direction: 'outgoing',
			},
			{
				label: 'Back',
				condition: { type: 'button_press', button: 'PS5_CIRCLE' },
				direction: 'outgoing',
			},
		],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},

	{
		id: 'builtin-quick-toggle',
		name: 'Quick Toggle',
		description: 'Hold modifier + press button to toggle features with rumble feedback.',
		category: 'code',
		tags: ['toggle', 'keyboard', 'quick'],
		nodeTemplate: {
			type: 'custom',
			label: 'Quick Toggle',
			variables: [
				{ name: 'feature_0_enabled', type: 'int', defaultValue: 0, persist: true },
				{ name: 'feature_1_enabled', type: 'int', defaultValue: 0, persist: true },
				{ name: 'feature_2_enabled', type: 'int', defaultValue: 0, persist: true },
			],
			gpcCode: [
				'// ========== Quick Toggle System ==========',
				'// Hold L3 + press button to toggle features',
				'',
				'function CheckToggles() {',
				'    if(get_val(PS5_L3)) {',
				'        if(event_press(PS5_UP)) {',
				'            feature_0_enabled = !feature_0_enabled;',
				'            if(feature_0_enabled) combo_run(RumbleOn);',
				'            else combo_run(RumbleOff);',
				'        }',
				'        if(event_press(PS5_DOWN)) {',
				'            feature_1_enabled = !feature_1_enabled;',
				'            if(feature_1_enabled) combo_run(RumbleOn);',
				'            else combo_run(RumbleOff);',
				'        }',
				'        if(event_press(PS5_LEFT)) {',
				'            feature_2_enabled = !feature_2_enabled;',
				'            if(feature_2_enabled) combo_run(RumbleOn);',
				'            else combo_run(RumbleOff);',
				'        }',
				'    }',
				'}',
			].join('\n'),
			onEnter: '',
			onExit: '',
			comboCode: [
				'combo RumbleOn {',
				'    set_rumble(RUMBLE_A, 80);',
				'    wait(150);',
				'    set_rumble(RUMBLE_A, 0);',
				'}',
				'',
				'combo RumbleOff {',
				'    set_rumble(RUMBLE_B, 40);',
				'    wait(80);',
				'    set_rumble(RUMBLE_B, 0);',
				'}',
			].join('\n'),
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
	{
		id: 'builtin-digital-clock',
		name: 'Digital Clock',
		description: 'OLED digital clock display with hours, minutes, seconds and blinking colon.',
		category: 'code',
		tags: ['oled', 'clock', 'display', 'timer'],
		nodeTemplate: {
			type: 'custom',
			label: 'Clock',
			variables: [
				{ name: 'clock_hours', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_minutes', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_seconds', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_timer', type: 'int', defaultValue: 0, persist: false },
				{ name: 'clock_colon_on', type: 'int', defaultValue: 1, persist: false },
			],
			gpcCode: [
				'// ========== Digital Clock Display ==========',
				'ClockTick();',
				'DrawClock();',
				'',
				'function ClockTick() {',
				'    clock_timer = clock_timer + get_rtime();',
				'    if(clock_timer >= 1000) {',
				'        clock_timer = clock_timer - 1000;',
				'        clock_seconds = clock_seconds + 1;',
				'        if(clock_seconds >= 60) {',
				'            clock_seconds = 0;',
				'            clock_minutes = clock_minutes + 1;',
				'            if(clock_minutes >= 60) {',
				'                clock_minutes = 0;',
				'                clock_hours = clock_hours + 1;',
				'                if(clock_hours >= 24) clock_hours = 0;',
				'            }',
				'        }',
				'        clock_colon_on = !clock_colon_on;',
				'    }',
				'}',
				'',
				'function DrawClock() {',
				'    // Hours',
				'    PrintNumber(clock_hours / 10, 1, 24, 20, OLED_FONT_MEDIUM);',
				'    PrintNumber(clock_hours % 10, 1, 36, 20, OLED_FONT_MEDIUM);',
				'',
				'    // Blinking colon',
				'    if(clock_colon_on) {',
				'        pixel_oled(50, 23, 1);',
				'        pixel_oled(50, 27, 1);',
				'    }',
				'',
				'    // Minutes',
				'    PrintNumber(clock_minutes / 10, 1, 54, 20, OLED_FONT_MEDIUM);',
				'    PrintNumber(clock_minutes % 10, 1, 66, 20, OLED_FONT_MEDIUM);',
				'',
				'    // Seconds (smaller)',
				'    PrintNumber(clock_seconds / 10, 1, 82, 24, OLED_FONT_SMALL);',
				'    PrintNumber(clock_seconds % 10, 1, 88, 24, OLED_FONT_SMALL);',
				'}',
			].join('\n'),
			onEnter: 'clock_timer = 0;',
			onExit: '',
			comboCode: '',
		},
		edgeTemplates: [],
		parameters: [],
		createdAt: 0,
		updatedAt: 0,
	},
];

export function getBuiltinChunk(id: string): FlowChunk | undefined {
	return BUILTIN_CHUNKS.find((c) => c.id === id);
}

export function getChunksByCategory(chunks: FlowChunk[]): Record<string, FlowChunk[]> {
	const grouped: Record<string, FlowChunk[]> = {};
	for (const chunk of chunks) {
		const cat = chunk.category || 'uncategorized';
		if (!grouped[cat]) grouped[cat] = [];
		grouped[cat].push(chunk);
	}
	return grouped;
}
