import type { FlowProject, FlowGraph, FlowVariable, ProfileSwitchConfig } from '$lib/types/flow';
import {
	generateFlowGpc,
	collectPersistVars,
	flowVarsToPersistVars,
	generateBitpackPersistence,
	type PersistVar,
} from './codegen';
import { generateGameplayGpc, generateGameplayGpcStandalone, generateWeaponDefaultsCode } from './codegen-gameplay';

/**
 * Generate a single merged GPC script from an entire FlowProject.
 *
 * Combines the menu flow (state machine) and gameplay flow (parallel modules)
 * into one cohesive script. Shared variables are declared once and used by both.
 *
 * Persistence is coordinated across both flows:
 *   - SPVAR_1 = data-exists marker
 *   - SPVAR_2-5 = reserved for user manual use
 *   - SPVAR_6+ = auto-generated bitpacked data
 */
export interface MergedFlowResult {
	code: string;
	extraFiles: Record<string, string>;
}

export interface MergedFlowOptions {
	/** Game version from game.json metadata (shown in header comment) */
	gameVersion?: number;
}

export function generateMergedFlowGpc(project: FlowProject, options?: MergedFlowOptions): MergedFlowResult {
	const menuFlow = project.flows.find((f) => f.flowType === 'menu');
	const gameplayFlow = project.flows.find((f) => f.flowType === 'gameplay');
	const dataFlow = project.flows.find((f) => f.flowType === 'data');

	const hasMenu = menuFlow && menuFlow.nodes.length > 0;
	const hasGameplay = gameplayFlow && gameplayFlow.nodes.some((n) => n.type === 'module' || n.type === 'custom');
	const hasData = dataFlow && dataFlow.nodes.some((n) => n.type === 'module' || n.type === 'custom');

	const profiles = project.profiles ?? [];
	// When weapon defaults are active with enabled vars, profiles are bypassed
	const weaponDefaultsActive =
		project.weaponDefaults &&
		project.weaponDefaults.enabledVars.length > 0 &&
		[...(gameplayFlow?.nodes ?? []), ...(dataFlow?.nodes ?? [])].some(
			(n) => n.moduleData?.moduleId === 'weapondata'
		);
	const profileCount = weaponDefaultsActive ? 0 : profiles.length;

	// If only one flow has content, just generate that one
	if (hasMenu && !hasGameplay && !hasData) {
		return { code: generateFlowGpc(menuFlow, profileCount), extraFiles: {} };
	}
	if (!hasMenu && hasGameplay && !hasData) {
		const gameplayResult = generateGameplayGpc(gameplayFlow!);
		return {
			code: generateGameplayGpcStandalone(gameplayFlow!),
			extraFiles: gameplayResult.extraFiles,
		};
	}
	if (!hasMenu && !hasGameplay && !hasData) {
		return { code: '// Empty flow project — add nodes to generate code\n', extraFiles: {} };
	}

	// Collect all module nodes across all flows for cross-flow checks (e.g. recoiltable)
	const allFlowModuleNodes = [
		...(gameplayFlow?.nodes ?? []),
		...(dataFlow?.nodes ?? []),
	].filter((n) => n.type === 'module' && n.moduleData);

	// Both flows have content — merge them
	// Skip persistence in menu codegen — we generate combined persistence below
	const dataResult = hasData ? generateGameplayGpc(dataFlow!, allFlowModuleNodes) : null;
	const gameplayResult = generateGameplayGpc(gameplayFlow!, allFlowModuleNodes);
	const menuCode = generateFlowGpc(menuFlow!, profileCount, { skipPersistence: true });

	// Generate weapon defaults code (if active)
	let weaponDefaultsResult: ReturnType<typeof generateWeaponDefaultsCode> = null;
	if (weaponDefaultsActive && project.weaponDefaults) {
		// Collect all variables from all flows to resolve enabled vars
		const allVars: FlowVariable[] = [
			...project.sharedVariables,
			...(menuFlow?.globalVariables ?? []),
			...(menuFlow?.nodes.flatMap((n) => n.variables) ?? []),
			...(gameplayFlow?.nodes.flatMap((n) => n.variables) ?? []),
			...(dataFlow?.nodes.flatMap((n) => n.variables) ?? []),
		];
		// Deduplicate by name
		const seen = new Set<string>();
		const uniqueVars = allVars.filter((v) => {
			if (seen.has(v.name)) return false;
			seen.add(v.name);
			return true;
		});

		const weaponNames =
			allFlowModuleNodes.find((n) => n.moduleData?.moduleId === 'weapondata')
				?.moduleData?.weaponNames ?? [];

		weaponDefaultsResult = generateWeaponDefaultsCode(
			project.weaponDefaults,
			weaponNames.length,
			uniqueVars,
			weaponNames
		);
	}

	// Collect combined persist vars from all sources (includes weapon defaults backup arrays)
	const combinedPersistVars = collectCombinedPersistVars(project, menuFlow!, gameplayFlow!, profileCount, dataFlow);

	const lines: string[] = [];

	lines.push(`// ====================================================`);
	lines.push(`// This script was generated by ZenForge.`);
	lines.push(`// If you want to make scripts easily maintainable`);
	lines.push(`// consider downloading the ZenForge for free at`);
	lines.push(`// https://github.com/masshirodev/zenforge`);
	lines.push(`// ====================================================`);
	lines.push(`// Project version: ${options?.gameVersion ?? project.version}`);
	lines.push(`// Generated at: ${new Date(project.updatedAt).toLocaleString()}`);

	if (profileCount > 1) {
		lines.push(`// Profiles: ${profiles.map((p) => p.name).join(', ')}`);
	}

	lines.push(`// ====================================================`);
	lines.push('');

	// Parse menu code to separate const declarations from functions
	// GPC requires const declarations before any function definitions
	const menuLines = menuCode.split('\n');
	const mainStartIdx = menuLines.findIndex((l) => l.trim().startsWith('main {'));
	const initStartIdx = menuLines.findIndex((l) => l.trim().startsWith('init {'));

	const sharedVarNames = new Set(project.sharedVariables.map((v) => v.name));

	// Collect gameplay + data variable names to avoid re-declaration in menu code
	const gameplayVarNames = new Set<string>();
	for (const decl of gameplayResult.variables) {
		const match = decl.match(/(?:int|int8|int16|int32)\s+(\w+)/);
		if (match) gameplayVarNames.add(match[1]);
	}
	if (dataResult) {
		for (const decl of dataResult.variables) {
			const match = decl.match(/(?:int|int8|int16|int32)\s+(\w+)/);
			if (match) gameplayVarNames.add(match[1]);
		}
	}

	// Everything before init is declarations/functions
	// Strip imports (already at top) and shared/gameplay variable re-declarations
	const preInit = menuLines
		.slice(0, initStartIdx >= 0 ? initStartIdx : mainStartIdx >= 0 ? mainStartIdx : menuLines.length)
		.filter((l) => {
			const trimmed = l.trim();
			if (trimmed.startsWith('import ')) return false;
			const varMatch = trimmed.match(/^(?:int|int8|int16|int32)\s+(\w+)/);
			if (varMatch && (sharedVarNames.has(varMatch[1]) || gameplayVarNames.has(varMatch[1]))) return false;
			return true;
		});

	// Split preInit into const declarations (string/image) and the rest (vars/functions)
	// Const declarations must appear before imports (which contain function defs)
	const constLines: string[] = [];
	const nonConstLines: string[] = [];
	let inConstBlock = false;
	for (const line of preInit) {
		const trimmed = line.trim();
		if (trimmed.startsWith('const string ') || trimmed.startsWith('const image ') || trimmed.startsWith('// ===== STRING TABLES') || trimmed.startsWith('// ===== IMAGE DATA')) {
			inConstBlock = true;
		}
		if (inConstBlock) {
			constLines.push(line);
			// End of a const block: closing brace of multi-line const or single-line const
			if (trimmed.startsWith('};') || (trimmed.startsWith('const ') && trimmed.endsWith(';'))) {
				inConstBlock = false;
			}
			// Empty line after const block
			if (trimmed === '' && constLines.length > 0) {
				inConstBlock = false;
			}
		} else {
			nonConstLines.push(line);
		}
	}

	// Profile variables (when multiple profiles are configured)
	if (profileCount > 1) {
		lines.push(`// ===== PROFILE SYSTEM =====`);
		lines.push(`define FLOW_PROFILE_COUNT = ${profileCount};`);
		lines.push(`int Flow_CurrentProfile = 0;`);

		// ProfileData module: emit labels array if the module exists in data/gameplay flow
		const hasProfileData = [...(dataFlow?.nodes ?? []), ...gameplayFlow!.nodes].some(
			(n) => n.moduleData?.moduleId === 'profiledata'
		);
		if (hasProfileData && profiles.length > 0) {
			const quoted = profiles.map((p) => `"${p.name}"`).join(', ');
			lines.push(`define PROFILE_COUNT = ${profileCount};`);
			lines.push(`const string ProfileLabels[] = { ${quoted} };`);
		}

		lines.push('');
	}

	// Array Builder: emit custom arrays from arraybuilder module nodes
	const arrayBuilderNodes = [...(dataFlow?.nodes ?? []), ...gameplayFlow!.nodes].filter(
		(n) => n.moduleData?.moduleId === 'arraybuilder' && n.moduleData.customArrays?.length
	);
	if (arrayBuilderNodes.length > 0) {
		lines.push(`// ===== CUSTOM ARRAYS =====`);
		for (const node of arrayBuilderNodes) {
			for (const arr of node.moduleData!.customArrays!) {
				if (arr.dimension === '2d') {
					const rows = arr.values2d ?? [];
					if (rows.length === 0) continue;
					// Flatten 2D into 1D with offset/count tables
					const flat: string[] = [];
					const offsets: number[] = [];
					const rowCounts: number[] = [];
					for (const row of rows) {
						offsets.push(flat.length);
						rowCounts.push(row.length);
						flat.push(...row);
					}
					lines.push(`define ${arr.countDefine} = ${rows.length};`);
					lines.push(`const int8 ${arr.name}_Offsets[] = { ${offsets.join(', ')} };`);
					lines.push(`const int8 ${arr.name}_RowCounts[] = { ${rowCounts.join(', ')} };`);
					const quoted = flat.map((v) => `"${v}"`).join(', ');
					lines.push(`const string ${arr.name}[] = { ${quoted} };`);
				} else {
					if (arr.values.length === 0) continue;
					lines.push(`define ${arr.countDefine} = ${arr.values.length};`);
					const quoted = arr.values.map((v) => `"${v}"`).join(', ');
					lines.push(`const string ${arr.name}[] = { ${quoted} };`);
				}
			}
		}
		lines.push('');
	}

	// Shared variables
	if (project.sharedVariables.length > 0) {
		lines.push(`// ===== SHARED VARIABLES =====`);
		for (const v of project.sharedVariables) {
			lines.push(...generateVarDecl(v, profileCount));
		}
		lines.push('');
	}

	// Shared code
	if (project.sharedCode.trim()) {
		lines.push(`// ===== SHARED CODE =====`);
		lines.push(project.sharedCode.trim());
		lines.push('');
	}

	// Gameplay variables (exclude any already declared as shared)
	const gameplayVars = gameplayResult.variables.filter((decl) => {
		const match = decl.match(/(?:int|int8|int16|int32)\s+(\w+)/);
		return match ? !sharedVarNames.has(match[1]) : true;
	});

	// Data defines and variables (emitted first — gameplay may reference them)
	if (dataResult) {
		const dataDefines = dataResult.defines;
		const dataVars = dataResult.variables.filter((decl) => {
			const match = decl.match(/(?:int|int8|int16|int32)\s+(\w+)/);
			return match ? !sharedVarNames.has(match[1]) : true;
		});
		if (dataDefines.length > 0) {
			lines.push(`// ===== DATA DEFINES =====`);
			lines.push(...dataDefines);
			lines.push('');
		}
		if (dataVars.length > 0) {
			lines.push(`// ===== DATA VARIABLES =====`);
			lines.push(...dataVars);
			lines.push('');
		}
	}

	// Gameplay defines (button params, weapon counts, etc.)
	if (gameplayResult.defines.length > 0) {
		lines.push(`// ===== GAMEPLAY DEFINES =====`);
		lines.push(...gameplayResult.defines);
		lines.push('');
	}

	if (gameplayVars.length > 0) {
		lines.push(`// ===== GAMEPLAY VARIABLES =====`);
		lines.push(...gameplayVars);
		lines.push('');
	}

	// Weapon defaults variables (backup arrays in "remember" mode)
	if (weaponDefaultsResult) {
		lines.push(`// ===== WEAPON DEFAULTS =====`);
		lines.push(...weaponDefaultsResult.varDecls);
		lines.push('');
	}

	// Emit const declarations (string tables, image data) before imports
	if (constLines.length > 0) {
		lines.push(...constLines);
		if (constLines[constLines.length - 1]?.trim() !== '') lines.push('');
	}

	// Imports for common helpers (after const declarations, since they contain functions)
	lines.push(`import common/helper;`);
	lines.push(`import common/oled;`);
	if (combinedPersistVars.length > 0) {
		lines.push(`import common/bitpack;`);
	}
	lines.push('');

	// Menu flow declarations and functions (non-const parts)
	lines.push(`// ===== MENU FLOW =====`);
	lines.push(...nonConstLines);

	// Data combos and functions (before gameplay — gameplay may reference them)
	if (dataResult) {
		if (dataResult.combos.length > 0) {
			lines.push(`// ===== DATA COMBOS =====`);
			lines.push(...dataResult.combos);
		}
		if (dataResult.functions.length > 0) {
			lines.push(`// ===== DATA FUNCTIONS =====`);
			lines.push(...dataResult.functions);
			lines.push('');
		}
	}

	// Gameplay combos
	if (gameplayResult.combos.length > 0) {
		lines.push(`// ===== GAMEPLAY COMBOS =====`);
		lines.push(...gameplayResult.combos);
	}

	// Gameplay functions
	if (gameplayResult.functions.length > 0) {
		lines.push(`// ===== GAMEPLAY FUNCTIONS =====`);
		lines.push(...gameplayResult.functions);
		lines.push('');
	}

	// Weapon defaults function (ApplyWeaponDefaults)
	if (weaponDefaultsResult && weaponDefaultsResult.functions.length > 0) {
		lines.push(`// ===== WEAPON DEFAULTS FUNCTION =====`);
		lines.push(...weaponDefaultsResult.functions);
	}

	// Combined persistence (bitpack-based, covers both flows)
	if (combinedPersistVars.length > 0) {
		lines.push(`// ===== PERSISTENCE =====`);
		lines.push(generateBitpackPersistence(combinedPersistVars));
		lines.push('');
	}

	// Merged init block
	const hasDataInit = dataResult && dataResult.initCode.length > 0;
	const hasGameplayInit = gameplayResult.initCode.length > 0;
	const hasWeaponDefaultsInit = weaponDefaultsResult && weaponDefaultsResult.initLines.length > 0;
	const needsInit = initStartIdx >= 0 || hasDataInit || hasGameplayInit || combinedPersistVars.length > 0 || hasWeaponDefaultsInit;

	if (needsInit) {
		lines.push(`// ===== INIT =====`);
		lines.push(`init {`);

		if (initStartIdx >= 0) {
			const initEndIdx = findBlockEnd(menuLines, initStartIdx);
			const menuInitBody = menuLines.slice(initStartIdx + 1, initEndIdx);
			if (hasGameplayInit) {
				lines.push(`    // --- Menu Init ---`);
			}
			lines.push(...menuInitBody);
		}

		if (hasDataInit) {
			if (initStartIdx >= 0) lines.push('');
			lines.push(`    // --- Data Init ---`);
			lines.push(...dataResult!.initCode);
		}

		if (hasGameplayInit) {
			if (initStartIdx >= 0 || hasDataInit) lines.push('');
			lines.push(`    // --- Gameplay Init ---`);
			lines.push(...gameplayResult.initCode);
		}

		if (combinedPersistVars.length > 0) {
			lines.push(`    Flow_Load();`);
		}

		// Weapon defaults init (after Flow_Load so backup arrays are restored)
		if (hasWeaponDefaultsInit) {
			lines.push(`    // --- Weapon Defaults Init ---`);
			lines.push(...weaponDefaultsResult!.initLines);
		}

		lines.push(`}`);
		lines.push('');
	}

	// Merged main block
	lines.push(`// ===== MAIN LOOP =====`);
	lines.push(`main {`);

	// Profile switching (before menu/gameplay code)
	if (profileCount > 1 && project.profileSwitch) {
		lines.push('');
		lines.push(`    // --- Profile Switching ---`);
		lines.push(...generateProfileSwitchCode(project.profileSwitch, profileCount));
	}

	// Weapon defaults: detect weapon change and apply defaults
	if (weaponDefaultsResult && weaponDefaultsResult.mainLoopLines.length > 0) {
		lines.push('');
		lines.push(...weaponDefaultsResult.mainLoopLines);
	}

	// Menu state dispatch (extract main body)
	if (mainStartIdx >= 0) {
		const mainEndIdx = findBlockEnd(menuLines, mainStartIdx);
		const menuMainBody = menuLines.slice(mainStartIdx + 1, mainEndIdx);
		lines.push(`    // --- Menu Flow ---`);
		lines.push(...menuMainBody);
	}

	// Data flow main loop (if any)
	if (dataResult && dataResult.mainLoopCode.length > 0) {
		lines.push('');
		lines.push(`    // --- Data Flow ---`);
		lines.push(...dataResult.mainLoopCode);
	}

	// Gameplay triggers
	if (gameplayResult.mainLoopCode.length > 0) {
		lines.push('');
		lines.push(`    // --- Gameplay Flow ---`);
		lines.push(...gameplayResult.mainLoopCode);
	}

	lines.push(`}`);

	const extraFiles = { ...gameplayResult.extraFiles, ...(dataResult?.extraFiles ?? {}) };
	return { code: lines.join('\n'), extraFiles };
}

// ==================== Persistence Collection ====================

/**
 * Collect all persist variables from a merged project, deduplicating by name.
 * Includes shared vars, menu flow vars, gameplay flow vars, and special
 * array persistence for Weapons_RecoilValues when applicable.
 */
export function collectCombinedPersistVars(
	project: FlowProject,
	menuFlow: FlowGraph,
	gameplayFlow: FlowGraph,
	profileCount: number,
	dataFlow?: FlowGraph
): PersistVar[] {
	const result: PersistVar[] = [];
	const seen = new Set<string>();

	function addVars(vars: FlowVariable[]) {
		const pvars = flowVarsToPersistVars(vars, profileCount);
		for (const pv of pvars) {
			if (!seen.has(pv.name)) {
				result.push(pv);
				seen.add(pv.name);
			}
		}
	}

	// Shared variables
	const sharedPersist = project.sharedVariables.filter((v) => v.persist);
	addVars(sharedPersist);

	// Data flow persist vars
	if (dataFlow) {
		addVars(collectPersistVars(dataFlow));
	}

	// Menu flow persist vars
	if (menuFlow.settings.persistenceEnabled) {
		addVars(collectPersistVars(menuFlow));
	}

	// Gameplay flow persist vars (module options with persist: true)
	addVars(collectPersistVars(gameplayFlow));

	// Weapons_RecoilValues persistence: basic/decay use full array, timeline uses sparse
	const allModuleNodes = [...gameplayFlow.nodes, ...(dataFlow?.nodes ?? [])];
	const hasWeapondata = allModuleNodes.some((n) => n.moduleData?.moduleId === 'weapondata');
	const hasBasicDecayRecoil = allModuleNodes.some(
		(n) =>
			n.moduleData?.needsWeapondata &&
			n.moduleData.moduleId !== 'weapondata' &&
			n.moduleData.moduleId !== 'antirecoil_timeline'
	);
	const hasTimeline = allModuleNodes.some((n) => n.moduleData?.moduleId === 'antirecoil_timeline');

	if (hasWeapondata && (hasBasicDecayRecoil || hasTimeline) && !seen.has('Weapons_RecoilValues')) {
		if (hasBasicDecayRecoil) {
			result.push({
				name: 'Weapons_RecoilValues',
				min: -100,
				max: 100,
				defaultValue: 0,
				arrayLoop: {
					countExpr: 'WEAPON_COUNT * 2',
					indexVar: '_bp_loop_i',
				},
			});
		} else {
			result.push({
				name: 'Weapons_RecoilValues',
				min: -100,
				max: 100,
				defaultValue: 0,
				sparseArray: {
					countExpr: 'WEAPON_COUNT',
					maxCount: 'WEAPON_COUNT',
					indexVar: '_bp_loop_i',
					countVar: '_bp_sparse_count',
					stride: 2,
				},
			});
		}
		seen.add('Weapons_RecoilValues');
	}

	// Weapon defaults backup arrays (only in "remember" mode)
	if (
		project.weaponDefaults?.rememberTweaks &&
		project.weaponDefaults.enabledVars.length > 0 &&
		hasWeapondata
	) {
		// Collect all variables from all flows to resolve enabled vars
		const allFlowVars: FlowVariable[] = [
			...project.sharedVariables,
			...menuFlow.globalVariables,
			...menuFlow.nodes.flatMap((n) => n.variables),
			...gameplayFlow.nodes.flatMap((n) => n.variables),
			...(dataFlow?.nodes.flatMap((n) => n.variables) ?? []),
		];
		const varMap = new Map<string, FlowVariable>();
		for (const v of allFlowVars) {
			if (!varMap.has(v.name)) varMap.set(v.name, v);
		}

		for (const varName of project.weaponDefaults.enabledVars) {
			const arrName = `_wd_${varName}`;
			if (seen.has(arrName)) continue;

			const v = varMap.get(varName);
			const min = v?.min ?? 0;
			const max = v?.max ?? (min === 0 && ((v?.defaultValue as number) ?? 0) <= 1 ? 1 : 100);

			result.push({
				name: arrName,
				min,
				max,
				defaultValue: (v?.defaultValue as number) ?? 0,
				sparseArray: {
					countExpr: 'WEAPON_COUNT',
					maxCount: 'WEAPON_COUNT',
					indexVar: `_bp_wd_i_${varName}`,
					countVar: `_bp_wd_c_${varName}`,
					stride: 1,
				},
			});
			seen.add(arrName);
		}
	}

	return result;
}

// ==================== Helpers ====================

function generateVarDecl(v: FlowVariable, profileCount: number = 0): string[] {
	if (v.perProfile && profileCount > 1 && v.type !== 'string') {
		const lines = [`${v.type} ${v.name}[${profileCount}];`];
		for (let i = 0; i < profileCount; i++) {
			lines.push(`${v.name}[${i}] = ${v.defaultValue};`);
		}
		return lines;
	}
	if (v.type === 'string') {
		const size = v.arraySize ?? 32;
		return [`int8 ${v.name}[${size}];`];
	}
	return [`${v.type} ${v.name} = ${v.defaultValue};`];
}

/**
 * Generate profile switch code for the main loop.
 */
function generateProfileSwitchCode(config: ProfileSwitchConfig, profileCount: number): string[] {
	const lines: string[] = [];
	const mod = config.modifier ? `get_val(${config.modifier}) && ` : '';

	lines.push(`    if(${mod}event_press(${config.next})) {`);
	lines.push(`        Flow_CurrentProfile = Flow_CurrentProfile + 1;`);
	lines.push(`        if(Flow_CurrentProfile >= ${profileCount}) Flow_CurrentProfile = 0;`);
	lines.push(`    }`);

	if (config.prev) {
		lines.push(`    if(${mod}event_press(${config.prev})) {`);
		lines.push(`        if(Flow_CurrentProfile > 0) Flow_CurrentProfile = Flow_CurrentProfile - 1;`);
		lines.push(`        else Flow_CurrentProfile = ${profileCount - 1};`);
		lines.push(`    }`);
	}

	return lines;
}

/**
 * Find the closing brace index for a block starting at `startIdx`.
 */
function findBlockEnd(lines: string[], startIdx: number): number {
	let depth = 0;
	for (let i = startIdx; i < lines.length; i++) {
		for (const ch of lines[i]) {
			if (ch === '{') depth++;
			if (ch === '}') depth--;
			if (depth === 0 && i > startIdx) return i;
		}
	}
	return lines.length - 1;
}
